-- ============================================
-- 🔐 VASTA SECURITY HARDENING - AUDIT SCHEMA
-- ============================================
-- Execute this in Supabase SQL Editor
-- 
-- Tabela de auditoria para rastrear ações sensíveis
-- e detectar atividades suspeitas.
-- ============================================

-- =====================
-- SECURITY AUDIT LOGS TABLE
-- =====================
CREATE TABLE IF NOT EXISTS public.security_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Contexto do usuário
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  tenant_id bigint REFERENCES public.tenants(id) ON DELETE SET NULL,
  
  -- Detalhes da ação
  action text NOT NULL, -- ex: 'login', 'profile_update', 'order_created', 'suspicious_activity'
  resource_type text,   -- ex: 'profile', 'product', 'order'
  resource_id text,     -- ID do recurso afetado
  
  -- Metadados adicionais
  ip_address inet,
  user_agent text,
  metadata jsonb DEFAULT '{}',
  
  -- Timestamps
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Comentários para documentação
COMMENT ON TABLE public.security_audit_logs IS 'Registro de auditoria de segurança para ações sensíveis';
COMMENT ON COLUMN public.security_audit_logs.action IS 'Tipo de ação: login, logout, profile_update, order_created, password_change, etc';
COMMENT ON COLUMN public.security_audit_logs.metadata IS 'Dados adicionais específicos da ação em formato JSON';

-- =====================
-- RLS POLICIES
-- =====================
ALTER TABLE public.security_audit_logs ENABLE ROW LEVEL SECURITY;

-- Usuários podem ver apenas logs do seu tenant
CREATE POLICY "Users view own tenant audit logs" ON public.security_audit_logs
  FOR SELECT USING (
    tenant_id = get_user_tenant_id()
  );

-- Nenhuma policy INSERT/UPDATE/DELETE para usuários normais
-- Inserção apenas via service_role ou funções SECURITY DEFINER

-- =====================
-- INDEXES
-- =====================
CREATE INDEX IF NOT EXISTS idx_audit_logs_user 
  ON public.security_audit_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant 
  ON public.security_audit_logs(tenant_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created 
  ON public.security_audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action 
  ON public.security_audit_logs(action);

-- Índice composto para queries comuns
CREATE INDEX IF NOT EXISTS idx_audit_logs_tenant_created 
  ON public.security_audit_logs(tenant_id, created_at DESC);

-- =====================
-- TRIGGER: Auto-log de ações críticas
-- =====================

-- Trigger para logar deleções de produtos
CREATE OR REPLACE FUNCTION log_product_deletion()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.security_audit_logs (
    user_id,
    tenant_id,
    action,
    resource_type,
    resource_id,
    metadata
  ) VALUES (
    auth.uid(),
    get_user_tenant_id(),
    'product_deleted',
    'product',
    OLD.id::text,
    jsonb_build_object(
      'title', OLD.title,
      'price', OLD.price
    )
  );
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_log_product_deletion ON public.products;
CREATE TRIGGER trigger_log_product_deletion
  BEFORE DELETE ON public.products
  FOR EACH ROW EXECUTE FUNCTION log_product_deletion();

-- Trigger para logar criação de orders
CREATE OR REPLACE FUNCTION log_order_creation()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.security_audit_logs (
    user_id,
    tenant_id,
    action,
    resource_type,
    resource_id,
    metadata
  ) VALUES (
    NEW.profile_id, -- O vendedor
    (SELECT tenant_id FROM public.profiles WHERE id = NEW.profile_id),
    'order_created',
    'order',
    NEW.id::text,
    jsonb_build_object(
      'amount', NEW.amount,
      'buyer_email', NEW.buyer_email,
      'product_id', NEW.product_id
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_log_order_creation ON public.orders;
CREATE TRIGGER trigger_log_order_creation
  AFTER INSERT ON public.orders
  FOR EACH ROW EXECUTE FUNCTION log_order_creation();

-- =====================
-- VIEWS ÚTEIS (para dashboard de segurança)
-- =====================

-- View de atividade recente do tenant
CREATE OR REPLACE VIEW public.my_security_activity AS
SELECT 
  action,
  resource_type,
  resource_id,
  metadata,
  created_at
FROM public.security_audit_logs
WHERE tenant_id = get_user_tenant_id()
ORDER BY created_at DESC
LIMIT 100;

-- Permitir acesso à view para usuários autenticados
GRANT SELECT ON public.my_security_activity TO authenticated;
